name: tree_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - numpy=1.19.5
  - pandas=1.1.5
  - networkx=2.5.1
  - scikit-learn=0.24.2
  - h5py=3.1.0
  - pip:
    - tensorflow==2.6.2
    - Keras==2.6.0
    - shap==0.41.0